# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: X-Monit
email: pkcinna@xmonit.com
description: >-
  Custom Monitoring and Automation Software
  <br /><br />    
  Advanced automation with Arduino Mega, Raspberry PI, Prometheus, Nagios, Icinga, OpenHAB, IFTTT, etc...
twitter_username: pkcinna01
github_username:  pkcinna01
facebook_username:  pkcinna01

# Build settings
markdown: kramdown
#theme: jekyll-theme-startbootstrap-agency
plugins:
  - jekyll-feed
  - jekyll-sitemap

sass: 
  style: compressed 

permalink: pretty

#collections:
#  projects:

defaults:
  -
    path: ""
    type: post
    values:
      page.description: blah

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
